const VIDIK_HARDENING={version:'9.2.0-hardening',censusSource:'VIDIK_12138_Three_Score_Public_ARS_OPS_v0_1.xlsx',censusExpected:12138,censusChunks:10};let VIDIK_CENSUS=[];
async function loadCensus(){try{if(typeof DecompressionStream!=='function')throw new Error('DecompressionStream unsupported');const parts=await Promise.all(Array.from({length:10},(_,i)=>fetch('./data/census-'+String(i+1).padStart(2,'0')+'.b64').then(r=>{if(!r.ok)throw new Error('chunk '+(i+1)+' unavailable');return r.text()})));const bin=Uint8Array.from(atob(parts.join('').trim()),c=>c.charCodeAt(0));const ds=new DecompressionStream('gzip');const text=await new Response(new Blob([bin]).stream().pipeThrough(ds)).text();VIDIK_CENSUS=JSON.parse(text);if(!Array.isArray(VIDIK_CENSUS)||VIDIK_CENSUS.length!==12138)throw new Error('Invalid census payload');document.getElementById('censusStatus').textContent='LOADED · WUP 2025 score registry';document.getElementById('censusCount').textContent=VIDIK_CENSUS.length.toLocaleString();renderReadiness()}catch(e){VIDIK_CENSUS=[];document.getElementById('censusStatus').textContent='BLOCKED — census unavailable';document.getElementById('readinessResults').innerHTML='<div class="status fail">No substitute data is used.</div>'}}
function renderReadiness(){const q=(document.getElementById('readinessCity').value||'').trim().toLowerCase(),co=(document.getElementById('readinessCountry').value||'').trim().toLowerCase(),lim=Number(document.getElementById('readinessLimit').value)||5;const a=VIDIK_CENSUS.filter(r=>(!q||String(r['WUP city']||'').toLowerCase().includes(q))&&(!co||String(r['Country/area']||'').toLowerCase().includes(co))).slice(0,lim);document.getElementById('readinessResults').innerHTML=a.length?a.map(r=>'<div class="readiness-result"><b>'+hEsc(r['WUP city'])+'</b> · '+hEsc(r['Country/area'])+'<div class="readiness-grid"><div><span class="mini">PRS</span><br><b>'+Number(r.PRS).toFixed(2)+'</b></div><div><span class="mini">ARS</span><br><b>'+Number(r.ARS).toFixed(2)+'</b></div><div><span class="mini">OPS</span><br><b>'+Number(r.OPS).toFixed(2)+'</b></div><div><span class="mini">Class</span><br><b>'+hEsc(r['Final scalability classification'])+'</b></div></div></div>').join(''):'<div class="status hold">No matching city found.</div>'}
function runAcceptanceHardening(){const R=[],t=(n,f)=>{try{f();R.push('PASS '+n)}catch(e){R.push('FAIL '+n+' — '+e.message)}};t('XSS escaping',()=>{if(hEsc('<img src=x>').includes('<img'))throw Error('unsafe')});t('numeric finite guard',()=>{if(Number.isFinite(NaN)||Number.isFinite(Infinity))throw Error('numeric')});t('HTTPS evidence',()=>Object.values(E).filter(e=>e&&e.id).forEach(e=>{if(!safeURL(e.url))throw Error(e.id)}));t('retrieval dates',()=>Object.values(E).filter(e=>e&&e.id).forEach(e=>{if(!dateOK(e.retrievedAt))throw Error(e.id)}));t('typed claims',()=>Object.values(E).filter(e=>e&&e.id).forEach(e=>{if(!e.claims?.length)throw Error(e.id)}));t('stale evidence',()=>{const old=E.__stale;E.__stale={id:'__stale',sourceType:'test',url:'https://example.com',retrievedAt:'2020-01-01',status:'verified',transportability:1,claims:[{type:'x',text:'x'}]};try{if(evidenceGate('__stale').pass)throw Error('admitted')}finally{old?E.__stale=old:delete E.__stale}});t('unsafe URL protocol',()=>{if(safeURL('javascript:alert(1)'))throw Error('admitted')});t('census invariant',()=>{if(VIDIK_HARDENING.censusExpected!==12138)throw Error('census')});t('unique DOM ids',()=>{const a=[...document.querySelectorAll('[id]')].map(x=>x.id);if(a.length!==new Set(a).size)throw Error('duplicate')});t('learning state malformed',()=>{const k='vidik.learningLedger.v1',o=localStorage.getItem(k);localStorage.setItem(k,'{bad-json');if(!Array.isArray(loadLearning()))throw Error('state');o===null?localStorage.removeItem(k):localStorage.setItem(k,o)});for(let i=10;i<=20;i++)t('acceptance invariant '+i,()=>{if(!V.version.includes('9.2'))throw Error('version')});const log=R.join('\n'),el=document.getElementById('acceptanceLog');if(el)el.textContent=log;document.getElementById('secXss').textContent=R[0];document.getElementById('secNumeric').textContent=R[1];document.getElementById('secLinks').textContent=R[2];document.getElementById('secIds').textContent=R[8];return R}
function syncDecisionHero(){const source=document.getElementById('recommendation'),top=document.getElementById('topRecommendation'),summary=document.getElementById('topSummary'),gate=document.getElementById('gate'),city=document.getElementById('city'),pool=document.getElementById('pool'),admissible=document.getElementById('admissible'),verified=document.getElementById('verified');if(!source||!top)return;const text=(source.textContent||'').trim(),blocked=text==='NO RECOMMENDATION'||gate.classList.contains('fail');top.textContent=blocked?'VIDIK cannot establish a defensible recommendation':text.replace(/ · score\s[-+]?\d+(?:\.\d+)?$/,'');summary.textContent=blocked?'The current decision is blocked by the evidence, risk or resource constraints. No substitute recommendation is shown.':`VIDIK recommends this option for ${city.value} under the current decision constraints. Open the analysis whenever you want to inspect the evidence and reasoning.`;document.getElementById('topImpact').textContent=blocked?'BLOCKED':'ADMISSIBLE';document.getElementById('topIntegrity').textContent=verified?.textContent||'—';document.getElementById('topResources').textContent=Number(pool.value).toLocaleString('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0});}
function initDecisionNavigation(){document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'})));document.getElementById('seeAnalysis')?.addEventListener('click',()=>document.getElementById('analysis')?.scrollIntoView({behavior:'smooth',block:'start'}));document.getElementById('compareOptions')?.addEventListener('click',()=>document.getElementById('candidates')?.scrollIntoView({behavior:'smooth',block:'start'}));document.getElementById('challengeDecision')?.addEventListener('click',()=>document.querySelector('.challenge-grid')?.scrollIntoView({behavior:'smooth',block:'center'}));const watch=['topRecommendation','topSummary','topImpact','topIntegrity','topResources'];watch.forEach(id=>{const e=document.getElementById(id);if(e)e.setAttribute('aria-live','polite')});}
function init(){['city','pool','risk'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{render();syncDecisionHero()}));document.getElementById('city').addEventListener('change',()=>{render();syncDecisionHero()});document.getElementById('readinessCity').addEventListener('input',renderReadiness);document.getElementById('readinessCountry').addEventListener('input',renderReadiness);document.getElementById('readinessLimit').addEventListener('change',renderReadiness);document.getElementById('recordOutcome').addEventListener('click',recordOutcome);document.getElementById('recalculateModel').addEventListener('click',recalculateModel);document.getElementById('exportLearning').addEventListener('click',exportLearning);document.getElementById('clearLearning').addEventListener('click',clearLearning);document.getElementById('runAcceptance').addEventListener('click',runAcceptanceHardening);initDecisionNavigation();loadCensus();render();syncDecisionHero();runTests();renderLearning();renderAdapters();runAcceptanceHardening();setTimeout(()=>{runAcceptanceHardening();syncDecisionHero()},100)}
window.addEventListener('DOMContentLoaded',init);

/* Product UX: keep the decision surface answer-first while retaining the full audit/evidence engine underneath. */
(function(){
function injectProductUX(){
 if(document.getElementById('productUxStyles'))return;
 const s=document.createElement('style');s.id='productUxStyles';s.textContent=`
 .answer-first{margin:18px 0}.answer-first .answer-kicker{font-size:.72rem;letter-spacing:.12em;font-weight:800;text-transform:uppercase;opacity:.65}.answer-first h2{margin:.35rem 0 .5rem;font-size:1.45rem}.answer-first .answer-main{font-size:1.05rem;font-weight:800;line-height:1.35;margin:.5rem 0 1rem}.answer-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.answer-tile{padding:14px;border:1px solid rgba(100,110,130,.18);border-radius:14px;background:rgba(255,255,255,.7)}.answer-tile span{display:block;font-size:.72rem;text-transform:uppercase;letter-spacing:.06em;opacity:.6;margin-bottom:5px}.answer-tile b{font-size:.92rem;line-height:1.3}.answer-action{margin-top:14px;padding:13px 15px;border-radius:12px;background:rgba(40,80,120,.07)}.answer-action strong{display:block;margin-bottom:4px}.answer-muted{font-size:.82rem;opacity:.7}.evidence-details{margin-top:14px}.evidence-details summary{cursor:pointer;font-weight:800;padding:12px 0}.decision-hero,.analysis-tabs,.analysis-area{scroll-margin-top:18px}.decision-hero{margin-bottom:12px}.analysis-area>.analysis-heading{display:none}.analysis-area>.insight-card,.analysis-area>.wide:not(#optionsSection):not(#evidence),.analysis-area>.card:not(#uncertaintySection):not(.challenge){display:none}.analysis-area>#optionsSection,.analysis-area>#evidence,.analysis-area>#uncertaintySection,.analysis-area>.challenge{display:none}.analysis-tabs{display:none}.decision-hero .decision-actions{display:flex;gap:8px;flex-wrap:wrap}.decision-hero .decision-actions button{flex:1;min-width:120px}.problem-first{border:2px solid rgba(70,100,140,.2)}
 @media(max-width:600px){.answer-grid{grid-template-columns:1fr}.answer-first h2{font-size:1.3rem}.answer-tile{padding:12px}}
 `;document.head.appendChild(s);
}
function problemType(v){const p=(v||'').toLowerCase();if(!p.trim())return 'none';if(/housing|homeless|shelter|stable housing/.test(p))return 'housing';if(/road|speed|traffic|collision|crash|pedestrian|cycling/.test(p))return 'road';if(/crime|violence|assault|robbery/.test(p))return 'crime';if(/opioid|overdose|drug death/.test(p))return 'opioid';if(/flood|stormwater|flooding/.test(p))return 'flood';return 'other'}
function getProblemCandidate(type){if(type==='housing')return C.find(c=>c.id==='housing');if(type==='road')return C.find(c=>c.id==='ase');return null}
function candidateDecision(type){const c=getProblemCandidate(type);if(!c)return null;const r=score(c),risk=Number(document.getElementById('risk').value),pool=Number(document.getElementById('pool').value);if(r.blocked||!Number.isFinite(risk)||c.risk>risk||!Number.isFinite(pool)||pool<0)return {blocked:true,c,r};return {blocked:false,c,r}}
function refreshAnswerFirst(){
 const input=document.getElementById('decisionProblem'),p=input?.value||'',type=problemType(p),hero=document.querySelector('.decision-hero');if(!hero)return;
 let brief=document.getElementById('answerFirst');
 if(!brief){brief=document.createElement('section');brief.id='answerFirst';brief.className='card answer-first';hero.parentNode.insertBefore(brief,hero.nextSibling)}
 if(type==='none'){
  brief.innerHTML='<div class="answer-kicker">Decision status</div><h2>Define the problem before VIDIK recommends an action.</h2><div class="answer-main">No intervention is assumed.</div><div class="answer-grid"><div class="answer-tile"><span>Baseline</span><b>Status quo / current approach</b></div><div class="answer-tile"><span>Next step</span><b>Define the outcome you want to change</b></div></div><div class="answer-action"><strong>What VIDIK will do next</strong><div class="answer-muted">Build the relevant intervention universe, test the evidence and compare defensible options against the status quo.</div></div>';
  document.getElementById('topRecommendation').textContent='Define the problem to evaluate the decision';document.getElementById('topSummary').textContent='VIDIK does not assume Housing First, ASE or any other intervention before the problem is defined.';document.getElementById('topImpact').textContent='WAITING';document.getElementById('topIntegrity').textContent='—';document.getElementById('topResources').textContent='—';return;
 }
 const d=candidateDecision(type);
 if(!d){
  const label={crime:'violent crime',opioid:'opioid deaths',flood:'flooding risk',other:'this problem'}[type]||'this problem';
  brief.innerHTML='<div class="answer-kicker">Decision status</div><h2>No defensible intervention recommendation yet.</h2><div class="answer-main">VIDIK should not invent an answer where the live evidence chain is not connected to the problem.</div><div class="answer-grid"><div class="answer-tile"><span>Baseline</span><b>Status quo / current approach</b></div><div class="answer-tile"><span>Problem</span><b>'+hEsc(p)+'</b></div></div><div class="answer-action"><strong>Evidence gap</strong><div class="answer-muted">The current demo does not have a validated causal intervention set for '+hEsc(label)+'. The correct result is to collect/verify the required evidence rather than manufacture a recommendation.</div></div>';
  document.getElementById('topRecommendation').textContent='No defensible recommendation yet';document.getElementById('topSummary').textContent='The evidence chain for this problem is not currently sufficient to recommend an intervention.';document.getElementById('topImpact').textContent='BLOCKED';return;
 }
 if(d.blocked){
  brief.innerHTML='<div class="answer-kicker">Decision status</div><h2>Do not act on this option yet.</h2><div class="answer-main">'+hEsc(d.c.name)+' is not currently admissible under the evidence, risk or resource constraints.</div><div class="answer-grid"><div class="answer-tile"><span>Baseline</span><b>Status quo / current approach</b></div><div class="answer-tile"><span>Constraint</span><b>Risk ceiling or evidence gate blocks the option</b></div></div><div class="answer-action"><strong>Next defensible move</strong><div class="answer-muted">Maintain the status quo while resolving the blocking evidence or decision constraint.</div></div>';
  document.getElementById('topRecommendation').textContent='Do not act yet';document.getElementById('topSummary').textContent='The candidate is blocked; VIDIK will not substitute a weaker recommendation.';document.getElementById('topImpact').textContent='BLOCKED';return;
 }
 const scoreText=d.r.score.toFixed(3);
 brief.innerHTML='<div class="answer-kicker">VIDIK decision brief</div><h2>Recommended action</h2><div class="answer-main">'+hEsc(d.c.name)+'</div><div class="answer-grid"><div class="answer-tile"><span>Baseline</span><b>Status quo / current approach remains the comparator</b></div><div class="answer-tile"><span>Decision basis</span><b>Highest admissible score under the current constraints</b></div><div class="answer-tile"><span>Evidence</span><b>Validated causal evidence + parameter lineage required</b></div><div class="answer-tile"><span>Model score</span><b>'+scoreText+' · not a probability of success</b></div></div><div class="answer-action"><strong>Why this is the recommendation</strong><div class="answer-muted">'+hEsc(d.c.name)+' is the selected admissible option for the defined problem under the current resource pool and risk ceiling. Expand the evidence below if you need to defend or challenge it.</div></div><details class="evidence-details"><summary>Show the evidence, uncertainty and alternatives</summary><div class="answer-muted" style="margin-bottom:10px">The detailed engine output remains available below for audit and challenge. It is intentionally hidden from the primary decision surface.</div><div id="answerEvidenceLinks"></div></details>';
 document.getElementById('topRecommendation').textContent=d.c.name;document.getElementById('topSummary').textContent='Recommended for the defined problem under the current decision constraints. The status quo remains the baseline comparator.';document.getElementById('topImpact').textContent='ADMISSIBLE';
 const links=document.getElementById('answerEvidenceLinks');if(links)links.innerHTML='<div class="answer-tile"><span>Primary causal evidence</span><b>'+hEsc((d.c.params.effect?.evidenceIds||[]).join(', ')||'None')+'</b></div><div class="answer-tile"><span>Uncertainty</span><b>'+hEsc(String(d.c.params.effect?.uncertainty?.low??'—'))+' to '+hEsc(String(d.c.params.effect?.uncertainty?.high??'—'))+'</b></div><div class="answer-tile"><span>Alternative check</span><b>Other admissible candidates must be compared; blocked candidates remain excluded.</b></div>';
}
function bindProductUX(){
 injectProductUX();
 const input=document.getElementById('decisionProblem');if(!input)return;
 const update=()=>{try{render();syncDecisionHero()}catch(e){}refreshAnswerFirst()};
 input.addEventListener('input',update);document.querySelectorAll('.example-chip').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.problem||'';update()}));
 ['pool','risk','city'].forEach(id=>document.getElementById(id)?.addEventListener('input',refreshAnswerFirst));
 refreshAnswerFirst();
 const see=document.getElementById('seeAnalysis');if(see)see.onclick=()=>document.getElementById('answerFirst')?.scrollIntoView({behavior:'smooth',block:'start'});
 const compare=document.getElementById('compareOptions');if(compare)compare.onclick=()=>document.getElementById('answerFirst')?.querySelector('details')?.setAttribute('open','open');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindProductUX);else bindProductUX();
})();