const U=[
['public-safety',['status-quo','hot-spots policing','problem-oriented policing','focused deterrence','community violence intervention','place/environmental prevention','youth violence prevention','hospital-based violence intervention','victim services','justice-system diversion','police deployment/resource allocation','lighting/CCTV/place management']],
['housing',['status-quo','supportive housing','housing first','rapid rehousing','prevention/diversion','rent assistance','support services','new affordable housing supply','zoning/planning reform','shelter/service redesign']],
['health',['status-quo','prevention','harm reduction','treatment access','outreach','primary care expansion','mobile/community care','screening','public-health regulation','health-system coordination']],
['emergency-services',['status-quo','staffing expansion','station/location changes','deployment optimization','alternative response','co-response','community paramedicine','prevention','mutual aid/partnerships']],
['transport',['status-quo','road engineering','traffic calming','speed management','automated enforcement','intersection redesign','active transportation','transit service','parking/pricing','education/enforcement']],
['climate-water',['status-quo','green infrastructure','drainage/stormwater upgrades','flood protection','land-use controls','building standards','early warning','emergency preparedness','water conservation','asset renewal']],
['environment',['status-quo','collection/service redesign','recycling/organics','pricing/incentives','regulation','monitoring/enforcement','infrastructure investment','public education']],
['infrastructure',['status-quo','maintenance','renewal','replacement','new capital','condition-based prioritization','demand management','shared infrastructure','procurement changes']],
['economic',['status-quo','skills/training','business support','procurement/local purchasing','tax/fee incentives','infrastructure','placemaking','partnerships','targeted grants']],
['poverty',['status-quo','income supports','food programs','service navigation','targeted subsidies','affordable services','partnerships','prevention']],
['children-youth',['status-quo','early intervention','youth services','childcare','school/community partnerships','recreation','family supports','targeted prevention']],
['seniors-accessibility',['status-quo','accessible infrastructure','home/community supports','transport','service redesign','housing','digital access','partnerships']],
['parks-community',['status-quo','facility investment','programming','public-space redesign','maintenance','community partnerships','access programs']],
['planning',['status-quo','zoning reform','development standards','infrastructure sequencing','incentives','fees','public land strategy','planning process redesign']],
['municipal-operations',['status-quo','process redesign','digital service','staffing','procurement','shared services','automation','demand management','service-level redesign']],
['revenue',['status-quo','tax changes','fee changes','pricing','targeted subsidies','user charges','revenue diversification','expenditure reallocation']],
['governance',['status-quo','participatory processes','service transparency','information access','institutional redesign','partnerships','accountability mechanisms']]
];
const UNIVERSE_CANDIDATES=U.flatMap(([domain,classes])=>classes.map(name=>({id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name,domain,min:0,max:400000,dependsOn:[],risk:.5,params:{need:null,effect:null,capacity:null,feasibility:null,equity:null},evidence:[]})));
const C=[
{id:'housing',name:'Housing First / supportive housing',evidence:['ottawa-housing','housing-rct'],min:0,max:400000,dependsOn:[],risk:.22,params:{need:{value:.74,unit:'normalized',derivation:'Ottawa observed homelessness-program demand context; normalized by documented decision rule v1',uncertainty:{low:.62,high:.84},evidenceIds:['ottawa-housing']},effect:{value:.42,unit:'absolute stable-housing probability difference',derivation:'RCT adjusted difference 73%-31%; bounded by reported 95% CI',uncertainty:{low:.36,high:.48},evidenceIds:['housing-rct'],causal:true},capacity:{value:.72,unit:'normalized implementation capacity',derivation:'Ottawa implementation output evidence plus explicit feasibility rubric',uncertainty:{low:.60,high:.82},evidenceIds:['ottawa-housing']},feasibility:{value:.76,unit:'normalized',derivation:'documented implementation-feasibility rubric using Ottawa observed delivery',uncertainty:{low:.65,high:.84},evidenceIds:['ottawa-housing']},equity:{value:.82,unit:'normalized',derivation:'normative policy weight, explicitly user-adjustable; not an empirical effect',uncertainty:{low:.82,high:.82},evidenceIds:[]}}},
{id:'ase',name:'Automated speed enforcement / speed management',evidence:['ase-eval','ottawa-road','ase-status'],min:0,max:400000,dependsOn:[],risk:.28,params:{need:{value:.70,unit:'normalized',derivation:'Ottawa fatal/major-injury road-safety baseline rubric',uncertainty:{low:.60,high:.80},evidenceIds:['ottawa-road']},effect:{value:.45,unit:'relative reduction in speeding proportion',derivation:'Toronto evaluation risk ratio 0.55 => 45% relative reduction in speeding; explicitly an intermediate outcome',uncertainty:{low:.35,high:.55},evidenceIds:['ase-eval'],causal:true},capacity:{value:.50,unit:'normalized',derivation:'current legal/operational constraint rubric',uncertainty:{low:.35,high:.65},evidenceIds:['ase-status']},feasibility:{value:.35,unit:'normalized',derivation:'legal-status constraint applied through feasibility rubric',uncertainty:{low:.20,high:.50},evidenceIds:['ase-status']},equity:{value:.60,unit:'normalized',derivation:'normative policy weight, explicitly user-adjustable; not an empirical effect',uncertainty:{low:.60,high:.60},evidenceIds:[]}}},
{id:'paramedic',name:'Additional paramedic capacity',evidence:['ottawa-budget'],min:0,max:400000,dependsOn:[],risk:.20,params:{need:{value:.68,unit:'normalized',derivation:'placeholder pending linked Ottawa EMS demand/outcome dataset',uncertainty:{low:.30,high:.90},evidenceIds:[]},effect:null,capacity:{value:.61,unit:'normalized',derivation:'budget-derived capacity availability',uncertainty:{low:.50,high:.72},evidenceIds:['ottawa-budget']},feasibility:{value:.74,unit:'normalized',derivation:'budget allocation evidence',uncertainty:{low:.62,high:.82},evidenceIds:['ottawa-budget']},equity:{value:.70,unit:'normalized',derivation:'normative policy weight, explicitly user-adjustable; not an empirical effect',uncertainty:{low:.70,high:.70},evidenceIds:[]}}}
];
for(const c of UNIVERSE_CANDIDATES)if(!C.some(x=>x.id===c.id))C.push(c);