'use strict';
(function(){
  const KEY='VIDIK_DECISION_LIFECYCLE_V9_5';
  const SCHEMA='VIDIK.DecisionLifecycle.v9.6.1';
  const CHECKPOINTS=new Set(['6mo','1yr','2yr','5yr','unspecified']);
  const CHECKPOINT_ALIASES=new Map([['6-month','6mo'],['6 month','6mo'],['1-year','1yr'],['1 year','1yr'],['2-year','2yr'],['2 year','2yr'],['5-year','5yr'],['5 year','5yr']]);
  const clone=x=>JSON.parse(JSON.stringify(x));
  function stable(x){if(Array.isArray(x))return '['+x.map(stable).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',');return JSON.stringify(x)}
  async function hash(value){const data=new TextEncoder().encode(stable(value));if(window.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(const n of data){h^=n;h=Math.imul(h,16777619)}return ('00000000'+(h>>>0).toString(16)).slice(-8)}
  async function digestRecord(r){const c=clone(r);delete c.integrityHash;return hash(c)}
  async function digestSnapshot(s){const c=clone(s);delete c.hash;return hash(c)}
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
  async function verifyRecord(r){if(!r||!r.integrityHash)return {ok:false,reason:'Missing lifecycle integrity seal'};if(r.snapshot){const snapHash=await digestSnapshot(r.snapshot);if(snapHash!==r.snapshot.hash)return {ok:false,reason:'Snapshot tampering detected'}}const actual=await digestRecord(r);if(actual!==r.integrityHash)return {ok:false,reason:'Lifecycle integrity mismatch',expected:r.integrityHash,actual};if(r.schema!==SCHEMA)return {ok:false,reason:'Unsupported lifecycle schema'};if(!Array.isArray(r.events)||!Array.isArray(r.outcomes))return {ok:false,reason:'Malformed lifecycle memory'};let previous='';for(const e of r.events){if(!e.eventHash||e.previousEventHash!==previous)return {ok:false,reason:'Lifecycle event-chain mismatch'};const body=clone(e);delete body.eventHash;const expected=await hash(body);if(expected!==e.eventHash)return {ok:false,reason:'Lifecycle event tampering detected'};previous=e.eventHash}return {ok:true}}
  async function verify(){return verifyRecord(read())}
  async function seal(r){r.integrityHash=await digestRecord(r);localStorage.setItem(KEY,JSON.stringify(r))}
  async function mutate(mutator){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};const v=await verifyRecord(r);if(!v.ok)return v;const next=clone(r);try{await mutator(next)}catch(e){return {ok:false,reason:e.message}}next.version=(next.version||1)+1;next.updatedAt=new Date().toISOString();next.events=next.events||[];const previous=next.events.at(-1)?.eventHash||'';const event={...next.pendingEvent,at:next.updatedAt,version:next.version,previousEventHash:previous};delete next.pendingEvent;event.eventHash=await hash(event);next.events.push(event);await seal(next);return {ok:true,record:clone(next)}}
  function decision(){return clone(window.VIDIK_DECISION_9_4||null)}
  function makeRecord(d){const integration=window.VIDIK_92_INTEGRATION?.decision,originalRecommendation=d?.recommendation??integration?.recommendation??null,createdAt=new Date().toISOString();return {schema:SCHEMA,decisionId:'VIDIK-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),version:1,status:'ANALYSIS',createdAt,updatedAt:createdAt,originalRecommendation,decisionObject:d,adoptedDecision:null,override:null,outcomes:[],calibration:null,drift:null,reviewSchedule:{checkpoints:['6mo','1yr','2yr','5yr']},events:[]}}
  async function persist(){const d=decision();if(!d||d.runtimeStatus!=='READY')return {ok:false,reason:'Decision is not READY'};const existing=read();if(existing){const v=await verifyRecord(existing);if(!v.ok)return v;return mutate(r=>{r.decisionObject=d;r.pendingEvent={type:'RECOMPUTE'}})}const r=makeRecord(d);const event={type:'DECISION_CREATED',at:r.createdAt,version:1,previousEventHash:''};event.eventHash=await hash(event);r.events=[event];await seal(r);render(r);return {ok:true,record:r}}
  async function snapshot(){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};const v=await verifyRecord(r);if(!v.ok)return v;const snap={schema:'VIDIK.DecisionSnapshot.v9.6.1',capturedAt:new Date().toISOString(),decisionId:r.decisionId,version:r.version,decisionObject:clone(r.decisionObject),originalRecommendation:r.originalRecommendation,adoptedDecision:r.adoptedDecision,override:r.override,outcomes:clone(r.outcomes),calibration:clone(r.calibration),drift:clone(r.drift),reviewSchedule:clone(r.reviewSchedule||null),parentEventHash:r.events.at(-1)?.eventHash||''};snap.hash=await digestSnapshot(snap);return mutate(x=>{x.snapshot=snap;x.pendingEvent={type:'SNAPSHOT',snapshotHash:snap.hash}})}
  async function overrideDecision(){const value=document.getElementById('lifecycleOverride')?.value?.trim(),rationale=document.getElementById('lifecycleRationale')?.value?.trim();if(!value||!rationale)return {ok:false,reason:'Override decision and rationale are required'};const r=read();if(!r)return {ok:false,reason:'Persist the decision first'};const v=await verifyRecord(r);if(!v.ok)return v;const result=await mutate(x=>{x.override={originalRecommendation:x.originalRecommendation,overriddenTo:value,rationale,actor:document.getElementById('lifecycleActor')?.value?.trim()||'human',at:new Date().toISOString()};x.adoptedDecision={recommendation:value,source:'HUMAN_OVERRIDE'};x.status='ADOPTED';x.pendingEvent={type:'HUMAN_OVERRIDE',overriddenTo:value}});if(!result.ok)return result;const snap=await snapshot();return snap.ok?{ok:true,record:snap.record}:{ok:false,reason:snap.reason||'Override snapshot failed'} }
  function finite(x){return typeof x==='number'&&Number.isFinite(x)}
  function validObservation(predicted,observed){return finite(predicted)&&finite(observed)&&Math.abs(predicted)<=1e12&&Math.abs(observed)<=1e12}
  function driftFor(outcomes){if(!outcomes?.length)return {status:'INSUFFICIENT_DATA',sampleSize:0,meanError:null,meanAbsoluteError:null};const errors=outcomes.map(o=>Number(o.observed)-Number(o.predicted)).filter(Number.isFinite);if(!errors.length)return {status:'INSUFFICIENT_DATA',sampleSize:0,meanError:null,meanAbsoluteError:null};const meanError=errors.reduce((a,b)=>a+b,0)/errors.length,mae=errors.reduce((a,b)=>a+Math.abs(b),0)/errors.length;return {status:errors.length>=2&&Math.abs(meanError)>Math.max(1,mae*.25)?'DRIFT_DETECTED':'STABLE',sampleSize:errors.length,meanError,meanAbsoluteError:mae}}
  function memory(){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};return {ok:true,decisionId:r.decisionId,status:r.status,version:r.version,originalRecommendation:r.originalRecommendation,adoptedDecision:r.adoptedDecision,override:r.override,outcomes:clone(r.outcomes||[]),events:clone(r.events||[]),snapshotHash:r.snapshot?.hash,integrityHash:r.integrityHash,calibration:r.calibration,drift:r.drift,reviewSchedule:clone(r.reviewSchedule||null)}}
  async function reviewOutcome(predicted,observed,checkpoint){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};predicted=Number(predicted);observed=Number(observed);const rawCheckpoint=String(checkpoint||'unspecified').trim().toLowerCase();const cp=CHECKPOINT_ALIASES.get(rawCheckpoint)||rawCheckpoint;if(!validObservation(predicted,observed))return {ok:false,reason:'Predicted and observed outcomes must be finite bounded numbers'};if(!CHECKPOINTS.has(cp))return {ok:false,reason:'Unsupported outcome checkpoint'};const result=await mutate(x=>{x.outcomes=x.outcomes||[];if(x.outcomes.some(o=>o.checkpoint===cp))throw new Error('Outcome checkpoint already recorded');x.outcomes.push({checkpoint:cp,predicted,observed,delta:observed-predicted,absoluteError:Math.abs(observed-predicted),recordedAt:new Date().toISOString()});x.status='REVIEWED';x.pendingEvent={type:'OUTCOME_REVIEW_V9_6',checkpoint:cp,delta:observed-predicted}});if(!result.ok)return result;return {ok:true,record:result.record,drift:driftFor(result.record.outcomes)}}
  async function recalibrate(targetParameterId){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};const v=await verifyRecord(r);if(!v.ok)return v;const target=String(targetParameterId||'').trim();if(!target)return {ok:false,reason:'Explicit calibration target parameter ID is required'};const d=driftFor(r.outcomes||[]);if(d.sampleSize<2)return {ok:false,reason:'At least two valid outcome observations are required for recalibration',drift:d};if(!finite(d.meanError)||Math.abs(d.meanError)>1e12)return {ok:false,reason:'Calibration adjustment is outside safe numeric bounds',drift:d};const baseline=r.calibration?.baseline??0;const result=await mutate(x=>{x.calibration={baseline,adjustment:d.meanError,method:'observed-minus-predicted mean error',sampleSize:d.sampleSize,updatedAt:new Date().toISOString(),sourceOutcomeCheckpoints:x.outcomes.map(o=>o.checkpoint),targetParameterId:target,application:'EXPLICIT_PARAMETER_MAPPING'};x.drift=d;x.pendingEvent={type:'RECALIBRATION',adjustment:d.meanError,sampleSize:d.sampleSize,targetParameterId:target}});if(!result.ok)return result;const snap=await snapshot();return snap.ok?{ok:true,record:snap.record,drift:d}:{ok:false,reason:snap.reason||'Recalibration snapshot failed'} }
  async function detectDrift(){const r=read();if(!r)return {ok:false,reason:'No persisted decision memory'};const v=await verifyRecord(r);if(!v.ok)return v;const d=driftFor(r.outcomes||[]);return {ok:true,drift:d}}
  function render(r){const s=document.getElementById('lifecycleStatus'),m=document.getElementById('decisionMemory');if(!s||!m)return;s.textContent=r?'Lifecycle: '+r.status+' | Decision '+r.decisionId+' | v'+r.version:'Lifecycle: NOT PERSISTED';m.textContent=r?JSON.stringify({decisionId:r.decisionId,status:r.status,version:r.version,originalRecommendation:r.originalRecommendation,adoptedDecision:r.adoptedDecision,override:r.override,outcomes:r.outcomes,snapshotHash:r.snapshot?.hash,integrityHash:r.integrityHash,calibration:r.calibration,drift:r.drift,reviewSchedule:r.reviewSchedule,events:r.events},null,2):''}
  function init(){render(read());document.getElementById('persistDecision')?.addEventListener('click',()=>persist().then(x=>{if(x.ok)render(x.record)}));document.getElementById('snapshotDecision')?.addEventListener('click',()=>snapshot().then(x=>{if(x.ok)render(x.record)}));document.getElementById('applyOverride')?.addEventListener('click',()=>overrideDecision().then(x=>{if(x.ok)render(x.record)}));document.getElementById('recordLifecycleOutcome')?.addEventListener('click',()=>reviewOutcome(document.getElementById('lifecyclePredicted')?.value,document.getElementById('lifecycleObserved')?.value,document.getElementById('lifecycleCheckpoint')?.value).then(x=>{if(x.ok)render(x.record)}));document.getElementById('v96ReviewOutcome')?.addEventListener('click',()=>reviewOutcome(document.getElementById('v96Predicted')?.value,document.getElementById('v96Observed')?.value,document.getElementById('v96Checkpoint')?.value).then(x=>{const e=document.getElementById('v96Status');if(e)e.textContent=x.ok?'Outcome recorded · recalibration available':'Outcome blocked: '+x.reason;render(x.record||read())}));document.getElementById('v96Recalibrate')?.addEventListener('click',()=>recalibrate(document.getElementById('v96CalibrationTarget')?.value).then(x=>{const e=document.getElementById('v96Status');if(e)e.textContent=x.ok?'Recalibration recorded · explicit target '+x.record.calibration.targetParameterId:'Recalibration blocked: '+x.reason;render(x.record||read())}));document.getElementById('v96DetectDrift')?.addEventListener('click',()=>detectDrift().then(x=>{const e=document.getElementById('v96Status');if(e)e.textContent=x.ok?'Drift: '+x.drift.status+' · n='+x.drift.sampleSize:'Drift detection blocked: '+x.reason}));window.VIDIK_DECISION_LIFECYCLE_9_6={persist,snapshot,overrideDecision,reviewOutcome,recalibrate,detectDrift,verify,memory,read}}
  window.addEventListener('DOMContentLoaded',init);
})();