const LEARNING_KEY='vidik.learningLedger.v1';
let learningWrite=Promise.resolve();
function loadLearning(){try{const v=JSON.parse(localStorage.getItem(LEARNING_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function renderLearning(){const a=loadLearning(),el=document.getElementById('learningLedger');if(el)el.textContent=a.length?JSON.stringify(a,null,2):'No persisted outcomes yet.';const st=document.getElementById('learningStoreStatus');if(st)st.textContent=a.length?(a.length+' outcome record(s) persisted.'):'No outcome recorded in this browser.'}
function updateRecalibration(){const a=loadLearning();if(!a.length||!window.VIDIK_DECISION_INTELLIGENCE_92?.recalibrate)return null;try{const r=window.VIDIK_DECISION_INTELLIGENCE_92.recalibrate({predictions:a.map(x=>x.predicted),observations:a.map(x=>x.observed)});localStorage.setItem(LEARNING_KEY,JSON.stringify(a.map((x,i)=>i===a.length-1?{...x,recalibration:r}:x)));return r}catch{return null}}
async function refreshDecisionAudit(){const integration=window.VIDIK_92_INTEGRATION;if(!integration?.recompute)return null;try{return await integration.recompute()}catch{return null}}
async function persistOutcome(){const status=document.getElementById('learningStoreStatus');try{const p=Number(document.getElementById('predictedOutcome')?.value),o=Number(document.getElementById('observedOutcome')?.value);if(!Number.isFinite(p)||!Number.isFinite(o)){if(status)status.textContent='BLOCKED — outcomes must be finite numbers.';return false}const a=loadLearning();a.push({recordedAt:new Date().toISOString(),checkpoint:document.getElementById('learningCheckpoint')?.value||'unspecified',predicted:p,observed:o,error:Number((o-p).toFixed(6)),recalibrationRequired:Math.abs(o-p)>Math.max(.1,Math.abs(p)*.2),modelVersion:window.VIDIK_DECISION_INTELLIGENCE_92?.version||window.VIDIK_HARDENING?.version||'unknown'});localStorage.setItem(LEARNING_KEY,JSON.stringify(a));updateRecalibration();renderLearning();await refreshDecisionAudit();renderLearning();return true}catch(e){if(status)status.textContent='BLOCKED — outcome could not be persisted.';renderLearning();return false}}
function recordOutcome(){learningWrite=learningWrite.then(()=>persistOutcome());return learningWrite}
async function recalculateModel(){await learningWrite;const r=updateRecalibration();await refreshDecisionAudit();renderLearning();const s=document.getElementById('learningStoreStatus');if(s)s.textContent=r?'Recalibration signal computed from persisted outcomes; material drift remains subject to human review.':'No outcomes available for recalibration.'}
function exportLearning(){const b=new Blob([JSON.stringify({version:window.VIDIK_DECISION_INTELLIGENCE_92?.version||window.VIDIK_HARDENING?.version,ledger:loadLearning()},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='VIDIK_learning_ledger_9_2.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function clearLearning(){learningWrite=learningWrite.then(()=>{localStorage.removeItem(LEARNING_KEY);renderLearning()});return learningWrite}
(function(){const css='.grid{grid-template-columns:repeat(12,minmax(0,1fr));align-items:start}.grid>.card{min-width:0;position:relative;isolation:isolate}pre{max-width:100%;overflow-wrap:anywhere;word-break:break-word}.grid>.card button,.grid>.card input,.grid>.card select{position:relative;z-index:100;pointer-events:auto}@media(max-width:800px){.grid{grid-template-columns:1fr}.card,.third,.wide{grid-column:1}.controls{grid-template-columns:1fr}.readiness-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';const s=document.createElement('style');s.textContent=css;document.head.appendChild(s)})();
