const { test, expect } = require('@playwright/test');

test.describe('VIDIK 9.2 canonical integration',()=>{
 test('canonical app loads and exposes integrated 9.2 state',async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.VIDIK_92_INTEGRATION?.status==='READY');const s=await page.evaluate(()=>window.VIDIK_92_INTEGRATION);expect(s.decision).toBeTruthy();expect(s.lineage.hash).toMatch(/^[0-9a-f]{64}$/);expect(s.sensitivity).toBeTruthy();expect(s.voi).toBeTruthy();});
 test('real recommendation is backed by real lineage',async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.VIDIK_92_INTEGRATION?.status==='READY');const s=await page.evaluate(()=>window.VIDIK_92_INTEGRATION);expect(s.decision.recommendation).toBeTruthy();expect(s.lineage.links.some(x=>x.parameterId.startsWith(s.decision.recommendation+':'))).toBeTruthy();});
 test('evidence mutation changes the canonical lineage hash',async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.VIDIK_92_INTEGRATION?.status==='READY');const before=await page.evaluate(()=>window.VIDIK_92_INTEGRATION.lastEvidenceHash);await page.evaluate(()=>{E['ottawa-housing'].notes='integration mutation test';});await page.evaluate(()=>window.VIDIK_92_INTEGRATION.recompute());const after=await page.evaluate(()=>window.VIDIK_92_INTEGRATION.lastEvidenceHash);expect(after).not.toBe(before);});
 test('outcome record feeds 9.2 recalibration lifecycle',async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.VIDIK_92_INTEGRATION?.status==='READY');await page.evaluate(async()=>{const lifecycle=window.VIDIK_DECISION_LIFECYCLE_9_6;const persisted=await lifecycle?.persist();if(!persisted?.ok)throw new Error('Failed to persist canonical decision lifecycle: '+(persisted?.reason||'unknown'));document.getElementById('predictedOutcome').value='0.4';document.getElementById('observedOutcome').value='0.7';await window.recordOutcome?.();});const r=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6?.memory());expect(r?.ok).toBe(true);expect(r.outcomes).toHaveLength(1);expect(r.outcomes[0]).toEqual(expect.objectContaining({predicted:0.4,observed:0.7,checkpoint:'6-month'}));});
 test('snapshot tampering is rejected cryptographically',async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.VIDIK_92_INTEGRATION?.status==='READY');const result=await page.evaluate(async()=>{const d=window.VIDIK_DECISION_INTELLIGENCE_92;const s=await d.immutableDecisionSnapshot({decisionObject:{a:1},datasets:{census:'v1'},evidence:{snapshot:'e1'},parameters:{p:1}});s.snapshot.decision.a=2;return d.replaySnapshot(s,x=>({recommendation:x.decision.a}));});expect(result).toMatchObject({ok:false,reason:'SNAPSHOT_TAMPERED'});});
});
