const { test, expect } = require('@playwright/test');

test.describe('VIDIK 9.6.1 hardened decision lifecycle',()=>{
  async function ready(page){
    await page.goto('/');
    await page.evaluate(()=>{window.VIDIK_MUNICIPAL_RECONCILIATIONS={Ottawa:{status:'verified',schemaVersion:'geography-reconciliation.v1',identity:{geonameid:'100',name:'Ottawa',latitude:45.42,longitude:-75.69},enrichment:{provider:'WorldPop',geonameid:'100',population:100000},provenance:{identity:{provider:'GeoNames',asset:'cities500',record_id:'100'},enrichment:{provider:'WorldPop',record_id:'100'}},match:{method:'exact-or-normalized-name',score:1}}};return window.VIDIK_92_INTEGRATION.recompute()});
    await expect.poll(()=>page.evaluate(()=>window.VIDIK_DECISION_9_4?.runtimeStatus)).toBe('READY');
    await expect.poll(()=>page.evaluate(()=>!!window.VIDIK_DECISION_LIFECYCLE_9_5&&!!window.VIDIK_DECISION_LIFECYCLE_9_6)).toBe(true);
  }
  async function seed(page){await page.evaluate(()=>localStorage.removeItem('VIDIK_DECISION_LIFECYCLE_V9_5'));const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_5.persist());expect(x.ok).toBe(true);}
  test.beforeEach(async({page})=>{await ready(page);await seed(page)});
  test('retrieves persisted memory with a verifiable event chain',async({page})=>{const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.memory());expect(x.ok).toBe(true);expect(x.originalRecommendation).toBeTruthy();expect(x.events[0].eventHash).toBeTruthy();expect(x.events[0].previousEventHash).toBe('')});
  test('rejects tampered memory and refuses further mutation',async({page})=>{const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('VIDIK_DECISION_LIFECYCLE_V9_5')));await page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('VIDIK_DECISION_LIFECYCLE_V9_5'));r.originalRecommendation='ATTACKER';localStorage.setItem('VIDIK_DECISION_LIFECYCLE_V9_5',JSON.stringify(r))});const v=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.verify());expect(v.ok).toBe(false);expect(v.reason).toMatch(/integrity/i);const m=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,80,'6-month'));expect(m.ok).toBe(false);const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('VIDIK_DECISION_LIFECYCLE_V9_5')));expect(after.originalRecommendation).toBe('ATTACKER');expect(after.integrityHash).toBe(before.integrityHash)});
  test('rejects snapshot tampering',async({page})=>{await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_5.snapshot());await page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('VIDIK_DECISION_LIFECYCLE_V9_5'));r.snapshot.originalRecommendation='ATTACKER';localStorage.setItem('VIDIK_DECISION_LIFECYCLE_V9_5',JSON.stringify(r))});const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.verify());expect(x.ok).toBe(false);expect(x.reason).toMatch(/snapshot/i)});
  test('rejects duplicate outcome checkpoints',async({page})=>{expect((await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,82,'6-month'))).ok).toBe(true);const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,78,'6-month'));expect(x.ok).toBe(false);expect(x.reason).toMatch(/checkpoint/i)});
  test('requires two valid observations and an explicit target for recalibration',async({page})=>{const one=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,82,'6-month'));expect(one.ok).toBe(true);const tooSoon=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.recalibrate('candidate.effect'));expect(tooSoon.ok).toBe(false);expect(tooSoon.reason).toMatch(/two/i);await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,78,'1-year'));const noTarget=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.recalibrate());expect(noTarget.ok).toBe(false);expect(noTarget.reason).toMatch(/target/i);const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.recalibrate('housing:effect'));expect(x.ok).toBe(true);expect(x.record.calibration.targetParameterId).toBe('housing:effect');expect(x.record.calibration.application).toBe('EXPLICIT_PARAMETER_MAPPING')});
  test('detects systematic drift and preserves the evidence chain',async({page})=>{await page.evaluate(async()=>{await window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,70,'6-month');await window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,68,'1-year')});const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.detectDrift());expect(x.ok).toBe(true);expect(x.drift.status).toBe('DRIFT_DETECTED');expect(x.drift.sampleSize).toBe(2);expect(x.drift.meanError).toBe(-31);expect(await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.verify().then(x=>x.ok))).toBe(true)});
  test('fails closed on malformed numeric outcome',async({page})=>{const x=await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(Infinity,80,'6-month'));expect(x.ok).toBe(false);expect(x.reason).toMatch(/required/i)});
  test('applies explicitly mapped calibration to a subsequent recomputation',async({page})=>{await page.evaluate(async()=>{await window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,82,'6-month');await window.VIDIK_DECISION_LIFECYCLE_9_6.reviewOutcome(100,78,'1-year');await window.VIDIK_DECISION_LIFECYCLE_9_6.recalibrate('housing:effect')});const x=await page.evaluate(async()=>{await window.VIDIK_92_INTEGRATION.recompute();return {cal:window.VIDIK_92_INTEGRATION.calibration,decision:window.VIDIK_92_INTEGRATION.decision,raw:window.VIDIK_DECISION_9_4}});expect(x.cal).toBeTruthy();expect(x.cal.targetParameterId).toBe('housing:effect');expect(x.raw.recommendation).toBeTruthy();});
});
