const { test, expect } = require('@playwright/test');
const fs = require('fs');
const zlib = require('zlib');
const CHUNKS = Array.from({length:10},(_,i)=>`census-${String(i+1).padStart(2,'0')}.b64`);
function census(){const b=Buffer.concat(CHUNKS.map(n=>Buffer.from(fs.readFileSync(`data/${n}`,'utf8').trim(),'base64')));return JSON.parse(zlib.gunzipSync(b).toString('utf8'));}

test.describe('VIDIK 9.1.3 deep hostile validation',()=>{
 test('census integrity: 10 chunks combine to 12,138 unique records',async()=>{const rows=census();expect(rows).toHaveLength(12138);const ids=rows.map(r=>String(r.id??r.city_id??r.cityId??''));expect(ids.every(Boolean)).toBeTruthy();expect(new Set(ids).size).toBe(ids.length);expect(JSON.stringify(rows)).not.toMatch(/NaN|Infinity/);const text=JSON.stringify(rows).toLowerCase();for(const c of ['ottawa','toronto','melbourne'])expect(text).toContain(c);});
 test('browser loads complete census and all decision surfaces',async({page})=>{await page.goto('/');await expect(page.locator('#censusStatus')).toContainText('LOADED',{timeout:15000});await expect(page.locator('#censusCount')).toHaveText('12,138');for(const id of ['city','pool','risk','gate','recommendation','why','uncertainty','voi','audit','pipeline','candidates'])await expect(page.locator('#'+id)).toBeVisible();});
 test('decision matrix remains finite across cities, resources and risk',async({page})=>{await page.goto('/');for(const city of ['Ottawa','Toronto','Melbourne'])for(const pool of ['0','1','100000','1000000','100000000'])for(const risk of ['0','0.25','0.75','1']){await page.locator('#city').selectOption(city);await page.locator('#pool').fill(pool);await page.locator('#risk').fill(risk);await page.locator('#risk').press('Tab');expect((await page.locator('body').textContent())).not.toMatch(/NaN|Infinity/);}});
 test('negative resources fail closed at UI boundary',async({page})=>{await page.goto('/');await page.locator('#pool').evaluate(el=>{el.value='-1';el.dispatchEvent(new Event('input',{bubbles:true}));});await expect(page.locator('#gate')).toContainText('BLOCKED');await expect(page.locator('#recommendation')).toContainText('NO RECOMMENDATION');});
 test('risk bounds fail closed',async({page})=>{await page.goto('/');for(const value of ['-0.1','1.1']){await page.locator('#risk').evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await expect(page.locator('#gate')).toContainText('BLOCKED');}});
 test('city switching preserves census and audit identity',async({page})=>{await page.goto('/');for(const city of ['Ottawa','Toronto','Melbourne','Ottawa']){await page.locator('#city').selectOption(city);await expect(page.locator('#audit')).toContainText('"city": "'+city+'"');}await expect(page.locator('#censusCount')).toHaveText('12,138');});
 test('XSS payload is inert',async({page})=>{await page.goto('/');let fired=false;await page.exposeFunction('xssProbe',()=>{fired=true});await page.locator('#readinessCity').fill('<img src=x onerror="xssProbe()"><script>xssProbe()</script>');await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults img')).toHaveCount(0);await expect(page.locator('#readinessResults script')).toHaveCount(0);expect(fired).toBeFalsy();});
 test('learning round trip preserves audit',async({page})=>{await page.goto('/');await page.locator('#predictedOutcome').fill('100');await page.locator('#observedOutcome').fill('90');await page.locator('#recordOutcome').click();await page.locator('#recalculateModel').click();await expect(page.locator('#learningLedger')).toContainText('100');expect(await page.locator('#audit').textContent()).toContain('"city"');});
 test('built-in acceptance suite remains clean',async({page})=>{await page.goto('/');await page.locator('#runAcceptance').click();const log=await page.locator('#acceptanceLog').textContent();expect(log).not.toMatch(/FAIL/);expect((log.match(/PASS/g)||[]).length).toBeGreaterThanOrEqual(20);});
});
