const { test, expect } = require('@playwright/test');
const fs = require('fs');
const zlib = require('zlib');
const CHUNKS = Array.from({length:10},(_,i)=>`census-${String(i+1).padStart(2,'0')}.b64`);
function census(){const b=Buffer.concat(CHUNKS.map(n=>Buffer.from(fs.readFileSync(`data/${n}`,'utf8').trim(),'base64')));return JSON.parse(zlib.gunzipSync(b).toString('utf8'));}

test.describe('VIDIK 9.1.3 deep hostile validation',()=>{
 test('census integrity and required cities',async()=>{const rows=census();expect(rows).toHaveLength(12138);const names=rows.map(r=>String(r['WUP city']||'').toLowerCase());expect(names).toContain('ottawa');expect(names).toContain('toronto');expect(names).toContain('melbourne');expect(new Set(names).size).toBeGreaterThan(10000);expect(JSON.stringify(rows)).not.toMatch(/NaN|Infinity/);});
 test('browser loads complete census and critical surfaces',async({page})=>{await page.goto('/');await expect(page.locator('#censusStatus')).toContainText('LOADED',{timeout:15000});await expect(page.locator('#censusCount')).toHaveText('12,138');for(const id of ['city','pool','risk','gate','recommendation','why','uncertainty','voi','audit','pipeline','candidates'])await expect(page.locator('#'+id)).toBeAttached();});
 test('readiness search finds Ottawa Toronto Melbourne',async({page})=>{await page.goto('/');await expect(page.locator('#censusStatus')).toContainText('LOADED',{timeout:15000});for(const city of ['Ottawa','Toronto','Melbourne']){await page.locator('#readinessCity').fill(city);await expect(page.locator('#readinessResults')).toContainText(city,{timeout:5000});}});
 test('decision matrix remains finite across cities resources and risk',async({page})=>{await page.goto('/');for(const city of ['Ottawa','Toronto','Melbourne'])for(const pool of ['0','1','100000','1000000','100000000'])for(const risk of ['0','0.25','0.75','1']){await page.locator('#city').selectOption(city);await page.locator('#pool').fill(pool);await page.locator('#risk').fill(risk);await page.locator('#risk').press('Tab');expect(await page.locator('body').textContent()).not.toMatch(/NaN|Infinity/);}});
 test('negative resource input fails closed',async({page})=>{await page.goto('/');const pool=page.locator('#pool');await pool.fill('-1');await pool.dispatchEvent('input');await expect(page.locator('#gate')).toContainText('BLOCKED');await expect(page.locator('#recommendation')).toHaveText('NO RECOMMENDATION');});
 test('risk bounds fail closed',async({page})=>{await page.goto('/');for(const value of ['-0.1','1.1']){await page.locator('#risk').fill(value);await page.locator('#risk').dispatchEvent('input');await expect(page.locator('#gate')).toContainText('BLOCKED');}});
 test('city switching preserves audit identity',async({page})=>{await page.goto('/');for(const city of ['Ottawa','Toronto','Melbourne','Ottawa']){await page.locator('#city').selectOption(city);await expect(page.locator('#audit')).toContainText('"city": "'+city+'"');}await expect(page.locator('#censusCount')).toHaveText('12,138');});
 test('XSS payload is inert',async({page})=>{await page.goto('/');let fired=false;await page.exposeFunction('xssProbe',()=>{fired=true});await page.locator('#readinessCity').fill('<img src=x onerror="xssProbe()"><script>xssProbe()</script>');await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults img')).toHaveCount(0);await expect(page.locator('#readinessResults script')).toHaveCount(0);expect(fired).toBeFalsy();});
 test('learning round trip preserves audit',async({page})=>{await page.goto('/');await expect(page.locator('#audit')).toContainText('"city"',{timeout:10000});await page.evaluate(async()=>{const lifecycle=window.VIDIK_DECISION_LIFECYCLE_9_6;const persisted=await lifecycle?.persist();if(!persisted?.ok)throw new Error('Failed to persist canonical decision lifecycle: '+(persisted?.reason||'unknown'));});await page.locator('#predictedOutcome').fill('100');await page.locator('#observedOutcome').fill('90');await page.locator('#recordOutcome').click();await page.locator('#recalculateModel').click();await expect(page.locator('#learningLedger')).toContainText('100',{timeout:10000});await expect(page.locator('#audit')).toContainText('"city"',{timeout:10000});await expect.poll(async()=>await page.evaluate(()=>window.VIDIK_DECISION_LIFECYCLE_9_6?.memory()?.outcomes?.length)).toBe(1);});
 test('built-in acceptance suite remains clean',async({page})=>{await page.goto('/');await expect(page.locator('#acceptanceLog')).toContainText('PASS',{timeout:10000});await page.locator('#runAcceptance').click();await expect.poll(async()=>page.locator('#acceptanceLog').textContent()).not.toMatch(/FAIL/);const log=await page.locator('#acceptanceLog').textContent();expect((log.match(/PASS/g)||[]).length).toBeGreaterThanOrEqual(12);});
 test('all critical controls remain available on mobile',async({page})=>{await page.goto('/');for(const id of ['city','pool','risk','readinessCity','readinessCountry','readinessLimit','recordOutcome','recalculateModel','runAcceptance'])await expect(page.locator('#'+id)).toBeAttached();for(const id of ['city','pool','risk','readinessCity','readinessCountry','readinessLimit','recordOutcome','recalculateModel','runAcceptance'])await expect(page.locator('#'+id)).toBeEnabled();});
});
