const { test, expect } = require('@playwright/test');
const APP_PATH = '/';
async function openAnalysis(page){await page.locator('#seeAnalysis').click();}
async function openAdvanced(page,label){await page.locator('details.advanced').filter({hasText:label}).locator('summary').click();}

test('current engine loads and census reaches 12,138 records',async({page})=>{await page.goto(APP_PATH);await expect(page.locator('#censusStatus')).toContainText('LOADED');await expect(page.locator('#censusCount')).toHaveText('12,138')});
test('city selector changes decision context',async({page})=>{await page.goto(APP_PATH);await expect.poll(()=>page.locator('#did').textContent()).toMatch(/VIDIK-9\.2\.0-/);const before=await page.locator('#did').textContent();await page.locator('#city').selectOption('Toronto');await expect.poll(()=>page.locator('#did').textContent()).not.toBe(before);await expect.poll(()=>page.locator('body').evaluate(()=>window.VIDIK_92_INTEGRATION?.decision?.city)).toBe('Toronto');await page.locator('#city').selectOption('Melbourne');await expect(page.locator('#city')).toHaveValue('Melbourne');await expect.poll(()=>page.locator('#did').textContent()).toContain('melbourne');await expect.poll(()=>page.locator('body').evaluate(()=>window.VIDIK_92_INTEGRATION?.decision?.city)).toBe('Melbourne')});
test('resource and risk controls recompute',async({page})=>{await page.goto(APP_PATH);await page.locator('#pool').fill('250000');await page.locator('#pool').press('Tab');await page.locator('#risk').fill('0.25');await page.locator('#risk').press('Tab');await openAnalysis(page);await expect(page.locator('#recommendation')).toBeVisible();await expect(page.locator('#gate')).toBeVisible()});
test('why uncertainty VOI and audit populate',async({page})=>{await page.goto(APP_PATH);await forAnalysis(page);for(const id of ['why','uncertainty','voi','audit'])await expect.poll(()=>page.locator('#'+id).textContent()).toMatch(/./);await expect.poll(()=>page.locator('body').evaluate(()=>window.VIDIK_92_INTEGRATION?.status)).toBe('READY');await expect.poll(()=>page.locator('body').evaluate(()=>window.VIDIK_92_INTEGRATION?.revision)).toBeGreaterThan(0)});
test('municipal context is fail-closed when verified reconciliation is unavailable',async({page})=>{await page.goto(APP_PATH);const result=await page.evaluate(async()=>{delete window.VIDIK_MUNICIPAL_RECONCILIATIONS;delete window.VIDIK_MUNICIPAL_LIFECYCLE_10;await window.VIDIK_92_INTEGRATION.recompute();return {status:window.VIDIK_92_INTEGRATION?.decisionContextStatus,context:window.VIDIK_92_INTEGRATION?.decisionContext}});expect(result.status).toBe('BLOCKED');expect(result.context).toBeNull()});
test('verified reconciliation becomes the runtime decision context',async({page})=>{await page.goto(APP_PATH);const result=await page.evaluate(async()=>{window.VIDIK_MUNICIPAL_RECONCILIATIONS={Ottawa:{status:'verified',identity:{geonameid:'100',name:'Ottawa',latitude:45.42,longitude:-75.69},enrichment:{provider:'WorldPop',geonameid:'100',population:100000},provenance:{identity:{provider:'GeoNames',record_id:'100'},enrichment:{provider:'WorldPop',record_id:'100'}}}};await window.VIDIK_92_INTEGRATION.recompute();return window.VIDIK_92_INTEGRATION.decisionContext;});expect(result).toMatchObject({schemaVersion:'municipal-decision-context.v1',city:'Ottawa',identity:{provider:'GeoNames',recordId:'100'},population:{provider:'WorldPop',value:100000}})});
test('readiness search works for Ottawa Toronto Melbourne',async({page})=>{await page.goto(APP_PATH);await openAnalysis(page);for(const city of ['Ottawa','Toronto','Melbourne']){await page.locator('#readinessCity').fill(city);await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults')).toContainText(city)}});
test('built-in acceptance suite reports green',async({page})=>{await page.goto(APP_PATH);await openAnalysis(page);await openAdvanced(page,'Security, acceptance & adapters');await page.locator('#runAcceptance').scrollIntoViewIfNeeded();await page.locator('#runAcceptance').click({force:true});await expect.poll(()=>page.locator('#acceptanceLog').textContent()).toMatch(/PASS/);const text=await page.locator('#acceptanceLog').textContent();expect(text).not.toMatch(/FAIL/);expect((text.match(/PASS/g)||[]).length).toBeGreaterThanOrEqual(20)});
test('malicious UI input is escaped',async({page})=>{await page.goto(APP_PATH);await openAnalysis(page);await page.locator('#readinessCity').fill('<img src=x onerror=alert(1)>');await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults img')).toHaveCount(0)});
test('mobile critical controls usable',async({page})=>{await page.goto(APP_PATH);await openAnalysis(page);for(const id of ['city','pool','risk','recommendation'])await expect(page.locator('#'+id)).toBeVisible()});