const { test, expect } = require('@playwright/test');
const APP_PATH = '/';

test('9.1.3 loads and census reaches 12,138 records',async({page})=>{await page.goto(APP_PATH);await expect(page.locator('#censusStatus')).toContainText('LOADED');await expect(page.locator('#censusCount')).toHaveText('12,138')});
test('city selector changes decision context',async({page})=>{await page.goto(APP_PATH);const before=await page.locator('#did').textContent();await page.locator('#city').selectOption('Toronto');await expect.poll(()=>page.locator('#did').textContent()).not.toBe(before);await page.locator('#city').selectOption('Melbourne');await expect(page.locator('#city')).toHaveValue('Melbourne')});
test('resource and risk controls recompute',async({page})=>{await page.goto(APP_PATH);await page.locator('#pool').fill('250000');await page.locator('#pool').press('Tab');await page.locator('#risk').fill('0.25');await page.locator('#risk').press('Tab');await expect(page.locator('#recommendation')).toBeVisible();await expect(page.locator('#gate')).toBeVisible()});
test('why uncertainty VOI and audit populate',async({page})=>{await page.goto(APP_PATH);for(const id of ['why','uncertainty','voi','audit'])await expect(page.locator('#'+id)).toContainText(/./)});
test('readiness search works for Ottawa Toronto Melbourne',async({page})=>{await page.goto(APP_PATH);for(const city of ['Ottawa','Toronto','Melbourne']){await page.locator('#readinessCity').fill(city);await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults')).toContainText(city)}});
test('built-in acceptance suite reports green',async({page})=>{await page.goto(APP_PATH);await page.locator('#runAcceptance').click();const text=await page.locator('#acceptanceLog').textContent();expect((text.match(/PASS/g)||[]).length).toBeGreaterThanOrEqual(20)});
test('malicious UI input is escaped',async({page})=>{await page.goto(APP_PATH);await page.locator('#readinessCity').fill('<img src=x onerror=alert(1)>');await page.locator('#readinessCity').press('Tab');await expect(page.locator('#readinessResults img')).toHaveCount(0)});
test('mobile critical controls usable',async({page})=>{await page.goto(APP_PATH);for(const id of ['city','pool','risk','recommendation'])await expect(page.locator('#'+id)).toBeVisible()});
