'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const live=fs.readFileSync('js/live-decision-experience.js','utf8');
const journey=fs.readFileSync('js/interface-experience.js','utf8');
const variants=fs.readFileSync('js/interface-variants.js','utf8');
const shell=fs.readFileSync('js/decision-experience-v2.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles/decision-experience-v2.css','utf8');
assert.match(live,/vidik:decision-start/);
assert.doesNotMatch(live,/stopImmediatePropagation/);
assert.match(journey,/vidik:decision-start/);
assert.doesNotMatch(journey,/runDecision.*startJourney/);
assert.match(variants,/decision-experience-v2\.css/);
assert.doesNotMatch(variants,/newShellStyle/);
assert.doesNotMatch(variants,/newShellScript/);
assert.match(index,/styles\/decision-experience-v2\.css\?v=20260925-decision-v3/);
assert.match(index,/js\/decision-experience-v2\.js\?v=20260925-decision-v3/);
assert.match(shell,/CIVIC DECISION/);
assert.match(shell,/BUSINESS DECISION/);
assert.match(shell,/RESEARCH DECISION/);
assert.match(css,/data-workspace="municipal"/);
assert.match(css,/data-workspace="enterprise"/);
console.log('Decision experience shell + live journey wiring: PASS');
