'use strict';
const assert=require('assert');
const m=require('../src/full-scope/intelligence-hardening');
const cases={
1:()=>{const u=m.buildUniverseAudit('crime',[{id:'x',name:'x'}]);assert.deepEqual(u.unclassified,['x']);assert(u.searchRequired);},
2:()=>{const u=m.buildUniverseAudit('opioid',[{id:'a',name:'Treatment',families:['clinical'],sourceId:'a'},{id:'b',name:'Treatment',families:['direct-service'],sourceId:'b'}]);assert.equal(u.candidateCount,1);assert.deepEqual(u.candidates[0].sourceIds.sort(),['a','b']);assert(u.candidates[0].families.includes('clinical')&&u.candidates[0].families.includes('direct-service'));},
3:()=>{const u=m.buildUniverseAudit('flood',[null,{}, {id:'x',name:'Barrier',families:['infrastructure'],effect:999}]);assert.equal(u.candidateCount,1);assert.equal(u.candidates[0].effectsImported,false);},
4:()=>{const u=m.buildUniverseAudit('housing',[{id:'x',name:'Rent',families:['economic']}]);assert(u.completeness.familyCoverageRate<1);assert(u.searchRequired);},
5:()=>{const u=m.buildUniverseAudit('traffic',[{id:'x',name:'Road',families:['infrastructure']}]);const p=m.planEvidence(u,[{id:'s',evidenceTypes:['causal'],independenceGroup:'g'}],{x:{causal:{status:'supported'},implementation:{status:'supported'},cost:{status:'supported'},equity:{status:'supported'}});assert.deepEqual(p.candidatePlans[0].missing,['causal']);},
6:()=>{const u=m.buildUniverseAudit('heat',[{id:'x',name:'Cooling',families:['direct-service']}]);const p=m.planEvidence(u,[],{});assert.equal(p.blockedCount,1);assert.equal(p.candidatePlans[0].independentSourceGroupsAvailable,0);},
7:()=>{const g=m.causalGraph({id:'x'},[{sourceId:'s1',independenceGroup:'g',causalMethod:'quasi-experimental',verification:{status:'verified'},effect:1,effectUnit:'cases'},{sourceId:'s2',independenceGroup:'g',causalMethod:'difference-in-differences',verification:{status:'verified'},effect:2,effectUnit:'cases'}]);assert.equal(g.independentSourceGroups.length,1);assert(!g.causalReady);},
8:()=>{const g=m.causalGraph({id:'x'},[{sourceId:'s1',independenceGroup:'a',causalMethod:'randomized-trial',verification:{status:'verified'},effect:1,effectUnit:'rate'},{sourceId:'s2',independenceGroup:'b',causalMethod:'randomized-trial',verification:{status:'pending'},effect:1,effectUnit:'rate'}]);assert(!g.causalReady);assert(g.rejected.some(x=>x.reason==='independent-verification-missing'));},
9:()=>{const g=m.causalGraph({id:'x'},[{sourceId:'s1',causalMethod:'randomized-trial',verification:{status:'verified'},effect:Infinity,effectUnit:'rate'},{sourceId:'s2',independenceGroup:'b',causalMethod:'randomized-trial',verification:{status:'verified'},effect:1,effectUnit:'rate'}]);assert(!g.causalReady);assert(g.rejected.some(x=>x.reason==='independence-group-missing'));},
10:()=>{const t=m.transferability({population:100000,legalEnvironment:'CA'},{population:100000,legalEnvironment:'CA'});assert.equal(t.score,1);assert.equal(t.missingDimensions.length,7);assert(t.requiresLocalValidation);},
11:()=>{const t=m.transferability({population:100000,legalEnvironment:'CA',density:100},{population:100000,legalEnvironment:'US',density:100});assert(t.hardMismatch);assert.equal(t.band,'insufficient');},
12:()=>{const t=m.transferability({population:Infinity},{population:Infinity});assert.notEqual(t.band,'high');},
13:()=>{const a=m.allocate([{id:'a',effectUnit:'deaths',resourceUnit:'dollars',maxResource:100,effectAtMax:5},{id:'b',effectUnit:'incidents',resourceUnit:'dollars',maxResource:100,effectAtMax:7}],100);assert.equal(a.blockedReason,'incomparable-or-missing-units');},
14:()=>{const a=m.allocate([{id:'a',effectUnit:'cases',resourceUnit:'dollars',maxResource:100,step:10,fixedCost:60,effectAtMax:10}],100);assert.equal(a.selected[0].resource,40);assert.equal(a.remainingBudget,0);},
15:()=>{const a=m.allocate([{id:'bad',effectUnit:'cases',resourceUnit:'dollars',maxResource:-1,effectAtMax:5},{id:'zero',effectUnit:'cases',resourceUnit:'dollars',maxResource:10,effectAtMax:0},{id:'inf',effectUnit:'cases',resourceUnit:'dollars',maxResource:10,effectAtMax:Infinity},{id:'good',effectUnit:'cases',resourceUnit:'dollars',maxResource:10,step:5,effectAtMax:5}],5);assert.deepEqual(a.selected.map(x=>x.candidateId),['good']);},
16:()=>{const u=m.buildUniverseAudit('employment',[{id:'x',name:'Wage',families:['economic']}]);const p=m.planEvidence(u,[],{});const g=m.causalGraph({id:'x'},[]);const t=m.transferability({},{});const a=m.allocate([{id:'x',effectUnit:'cases',resourceUnit:'dollars',maxResource:1,effectAtMax:1}],1);[u,p,g,t,a].forEach(x=>assert.equal(x.recommendationAllowed,false));},
17:()=>{const u=m.buildUniverseAudit('housing',[{id:'x',name:'Rent',families:['economic']}]);assert(u.completeness.familyCoverageRate<1);},
18:()=>{const u=m.buildUniverseAudit('housing',[{id:'x',name:'Rent',families:['economic']}]);assert(u.searchRequired);}
};
const n=Number(process.argv[2]);if(!cases[n])throw new Error(`unknown-case:${process.argv[2]}`);cases[n]();console.log(`probe ${n}: PASS`);
