'use strict';
const assert=require('node:assert/strict');const test=require('node:test');const {createLearningLedger,appendOutcome,appendFailure,reviewDrift,validateLearningLedger}=require('../src/full-scope/learning-ledger');
async function ledger(){return createLearningLedger({problem:'reduce crime',candidateId:'x',baselineArtifactHash:'a'.repeat(64)})}
test('learning ledger is deeply immutable',async()=>{const l=await ledger();assert.equal(Object.isFrozen(l),true);assert.equal(Object.isFrozen(l.entries),true)});
test('learning append rejects a tampered prior ledger instead of laundering it',async()=>{const l=await ledger();const tampered=JSON.parse(JSON.stringify(l));tampered.problem='changed';await assert.rejects(()=>appendOutcome(tampered,{effect:10,unit:'incidents'},{effect:9,unit:'incidents'}),/learning-ledger-tampered/)});
test('learning append rejects malformed expected/observed units',async()=>{const l=await ledger();await assert.rejects(()=>appendOutcome(l,{effect:10,unit:'incidents'},{effect:9,unit:'dollars'}),/learning-outcome-invalid/)});
test('learning failure append remains mutation-free',async()=>{const l=await ledger();const n=await appendFailure(l,{severity:'critical',category:'evidence'});assert.equal(n.parameterMutationAllowed,false);assert.equal(n.automaticParameterUpdate,false);assert.equal(n.entries.length,1)});
test('learning ledger validation catches entry tampering',async()=>{const l=await ledger();const n=await appendFailure(l,{severity:'high',category:'source'});const t=JSON.parse(JSON.stringify(n));t.entries[0].failure.severity='low';const v=await validateLearningLedger(t);assert.equal(v.valid,false);assert.equal(v.reason,'learning-ledger-tampered')});
test('drift review cannot authorize parameter mutation',async()=>{let l=await ledger();l=await appendOutcome(l,{effect:10,unit:'incidents'},{effect:5,unit:'incidents'});const d=reviewDrift(l,.2);assert.equal(d.driftDetected,true);assert.equal(d.parameterMutationAllowed,false);assert.equal(d.automaticParameterUpdate,false)});
