'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync(require('node:path').join(__dirname,'../js/intervention-universe.js'),'utf8');
const context={window:{},console};vm.createContext(context);vm.runInContext(code,context);
const U=context.window.VIDIK_INTERVENTION_UNIVERSE;
assert.equal(context.window.VIDIK_INTERVENTION_UNIVERSE_VALIDATION.ok,true);
assert.ok(context.window.VIDIK_INTERVENTION_UNIVERSE_VALIDATION.count>=100);
const crime=context.window.vidikUniverseItemsForProblem('Minimize violent crime');
assert.ok(crime.length>=25);
assert.ok(crime.some(x=>x.name.includes('Status quo')));
assert.ok(crime.some(x=>x.name.includes('Hot-spots')));
assert.ok(crime.some(x=>x.name.includes('Mental-health')));
assert.ok(crime.some(x=>x.name.includes('Supportive housing')));
assert.ok(crime.some(x=>x.authority==='SHARED'));
const incomplete=context.window.vidikUniverseCoverage('Minimize violent crime',crime.slice(0,1).map(x=>x.id));
assert.equal(incomplete.complete,false);
assert.ok(incomplete.unresolved.length>0);
assert.ok(incomplete.coverageRatio<1);
const complete=context.window.vidikUniverseCoverage('Minimize violent crime',crime.map(x=>x.id));
assert.equal(complete.complete,true);
assert.equal(complete.unresolved.length,0);
assert.ok(U.domains.length>=15);
console.log('VIDIK municipal intervention universe: PASS');
