'use strict';
const assert=require('node:assert/strict');
const test=require('node:test');
const I=require('../js/production-intelligence');

const lead={id:'e:1',candidateId:'c1',sourceId:'openalex-works',evidenceLeadOnly:true,causalEffectImported:false,provenance:{externalId:'W1'}};
const verification={verified:true,verificationId:'v1',sourceId:'openalex-works',externalId:'W1',evidenceType:'causal',sourceJurisdiction:'international',targetJurisdiction:'Ottawa, Canada',localEvidenceBoundary:'explicit',transportability:{admissible:true},verifiedEvidence:['causal','implementation','cost','equity'],parameter:{estimate:.42,unit:'risk ratio',uncertainty:{low:.31,high:.56}}};

test('1 evidence promotion requires independent verified causal parameter',()=>{const r=I.promoteEvidence({lead,verification,targetJurisdiction:'Ottawa, Canada'});assert.equal(r.eligible,true);assert.equal(r.recommendationEligible,false);assert.equal(r.effectsImported,false);});
test('2 comparable-city intelligence never imports causal effects',()=>{const r=I.assessTransferability({problem:'pedestrian injuries',population:'large urban',institutionalCapacity:'high',implementationEnvironment:'urban',jurisdiction:'Ottawa'}, {problem:'pedestrian injuries',population:'large urban',institutionalCapacity:'high',implementationEnvironment:'urban',jurisdiction:'Toronto',evidenceBase:'study'});assert.equal(r.classification,'transferable-with-local-validation');assert.equal(r.causalEffectTransferred,false);assert.equal(r.evidenceImported,false);});
test('3 complete decision artifact preserves full decision chain and immutable hash',()=>{const r=I.buildDecisionArtifact({decisionId:'d1',problem:'reduce pedestrian injuries',jurisdiction:'Ottawa',discovery:{searched:12},candidates:['a','b'],evidence:['e1'],parameters:['p1'],uncertainty:{},optimization:{winner:'a'},recommendation:'a',why:'best admissible',whyNot:['b'],alternatives:['b'],humanOverride:null});assert.equal(r.schema,'VIDIK.DecisionArtifact.v1');assert.ok(r.immutableHash);assert.equal(r.statusQuo.explicit,true);});
test('4 outcome learning is append-only and does not mutate historical parameters',()=>{const r=I.recordOutcome({decisionId:'d1',immutableHash:'abc'},{checkpoint:'1-year',predicted:10,observed:13});assert.equal(r.deviation,3);assert.equal(r.baselineDecisionHash,'abc');assert.equal(r.historyRewrite,false);assert.equal(r.automaticParameterMutation,false);});
test('5 operational failures close recommendation path instead of substituting zero',()=>{const r=I.assessOperationalFailure({sourceStale:true,effectUnknown:true});assert.equal(r.safeToRecommend,false);assert.equal(r.recommendationEligible,false);assert.equal(r.unknownIsNotZero,true);assert.deepEqual(r.blockers,['source-stale','effect-unknown']);});
test('6 readiness gate reports exactly which engine layers remain',()=>{const r=I.buildReadiness({discoveryComplete:true,evidenceVerified:true,parametersAdmissible:true,optimizationValid:true,decisionArtifactPersisted:false,outcomeLearningReady:false});assert.equal(r.passed,4);assert.equal(r.total,6);assert.equal(r.complete,false);assert.equal(r.checks.decisionArtifact,false);});
