'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync(require('node:path').join(__dirname,'../js/vidik-platform-10.js'),'utf8');
const store=new Map();
const context={console,Date,Math,JSON,Number,String,Object,Array,window:{localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},},};
vm.createContext(context);vm.runInContext(code,context);
const P=context.window.VIDIK_PLATFORM_10;
assert.equal(P.VERSION,'10.0.0');
const d=P.createDecision({audience:'municipal',objective:'Improve housing stability',problem:'Improve housing stability',statusQuo:{description:'Current housing support baseline',baseline:100,source:'baseline-source'},interventionUniverse:[{id:'u1',name:'Housing interventions'}],options:[{id:'o1',name:'Option A',evidenceStatus:'SUPPORTED',expectedValue:0.8},{id:'o2',name:'Option B',evidenceStatus:'SUPPORTED',expectedValue:0.6}],evidence:[{id:'e1',quality:'high',transportability:1}],causalIdentification:{status:'SUPPORTED',rationale:'validated'},uncertainty:{overall:.25,components:[]},opportunityCost:{known:true,comparison:'status quo'},equity:{assessed:true,impacts:[]},constraints:{budget:1000000,implementation:[],legal:[],capacity:[]},provenance:[{source:'e1'}]});
assert.equal(P.validateDecision(d).ok,true);
assert.equal(P.scoreIntegrity(d).complete,true);
const ev=P.evaluate(d,(_,opts)=>({recommended:opts[0],ranked:opts}));
assert.equal(ev.ok,true);assert.equal(d.recommendation.id,'o1');
const voi=P.calculateVOI(d,[{id:'o2',expectedValue:1,informationCost:.1}]);
assert.equal(voi.recommendationCouldFlip,true);
const sens=P.sensitivity(d,[{id:'s1',recommendation:'o2',assumptions:{risk:.9}}]);
assert.equal(sens.recommendationFlips.length,1);
const snap=P.snapshot(d);assert.equal(snap.decisionId,d.id);
const persisted=P.persist(d);assert.equal(persisted.ok,true);assert.equal(P.getDecision(d.id).id,d.id);
const over=P.override(d,'actor','o2','Documented reason for adopting an alternative.');assert.equal(over.ok,true);
assert.equal(P.override(d,'actor','o2','').ok,false);
assert.equal(P.recordOutcome(d,'1-year',100,90).ok,true);assert.equal(P.detectDrift(d,.05).detected,true);
const artifact=P.exportArtifact(d);assert.equal(P.importArtifact(artifact).ok,true);
assert.equal(P.setKillSwitch(true,'maintenance').enabled,true);assert.equal(P.isKilled(),true);assert.equal(P.evaluate(d,()=>({recommended:d.options[0]})).code,'KILL_SWITCH');P.setKillSwitch(false);
const failure=P.recordFailure('TEST','Synthetic validation failure','info');assert.equal(P.listFailures().some(x=>x.id===failure.id),true);
console.log('VIDIK Platform 10 contract: PASS');
