'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const platform=fs.readFileSync(path.join(__dirname,'../js/vidik-platform-10.js'),'utf8');
const optimizer=fs.readFileSync(path.join(__dirname,'../js/municipal-budget-optimizer-10.js'),'utf8');
const budgetContract=fs.readFileSync(path.join(__dirname,'../js/vidik-platform-10-budget-contract.js'),'utf8');
const store=new Map();
const context={console,Date,Math,JSON,Number,String,Object,Array,URL,Blob,document:undefined,window:{localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}}};
vm.createContext(context);vm.runInContext(optimizer,context);vm.runInContext(platform,context);vm.runInContext(budgetContract,context);
const P=context.window.VIDIK_PLATFORM_10;
assert.equal(P.VERSION,'10.0.0');
const d=P.createDecision({audience:'municipal',objective:'Improve housing stability',problem:'Improve housing stability',statusQuo:{description:'Current housing support baseline',baseline:100,source:'baseline-source'},interventionUniverse:[{id:'housing',name:'Housing First'},{id:'ase',name:'Speed management'},{id:'paramedic',name:'Paramedic capacity'}],options:[{id:'housing',name:'Housing First',evidenceStatus:'SUPPORTED',expectedValue:0.8,cost:400000,maxCost:400000},{id:'ase',name:'Speed management',evidenceStatus:'SUPPORTED',expectedValue:0.6,cost:250000,maxCost:250000},{id:'paramedic',name:'Paramedic capacity',evidenceStatus:'SUPPORTED',expectedValue:0.5,cost:200000,maxCost:200000}],evidence:[{id:'e1',quality:'high',transportability:1}],causalIdentification:{status:'SUPPORTED',rationale:'validated'},uncertainty:{overall:.25,components:[]},opportunityCost:{known:true,comparison:'status quo'},equity:{assessed:true,impacts:[]},constraints:{budget:1000000,implementation:[],legal:[],capacity:[]},provenance:[{source:'e1'}]});
const budgets=P.generateMunicipalBudgetOptions({statusQuoBudget:1000000,requestedBudget:2000000,availableBudget:2500000,currency:'CAD',years:3});
assert.equal(budgets.ok,true);assert.equal(budgets.scope,'full-municipal');
for(const type of P.MUNICIPAL_BUDGET_TYPES)assert.ok(budgets.options.some(x=>x.type===type),`missing budget type ${type}`);
assert.ok(budgets.options.length>=19);
assert.equal(P.attachMunicipalBudgetOptions(d,{statusQuoBudget:1000000,requestedBudget:2000000,availableBudget:2500000,currency:'CAD',years:3}).ok,true);
assert.equal(d.budgetOptions.length,budgets.options.length);assert.equal(P.validateDecision(d).ok,true);assert.equal(P.scoreIntegrity(d).complete,true);
const portfolio=P.optimizeMunicipalPortfolio(d,'full-request');assert.equal(portfolio.scope,'full-municipal');assert.equal(portfolio.startingEnvelope,2000000);assert.equal(portfolio.selected.length,3);assert.ok(portfolio.unallocated>0);
const ev=P.evaluate(d,(_,opts)=>({recommended:opts[0],ranked:opts}));assert.equal(ev.ok,true);assert.equal(d.recommendation.id,'housing');
const voi=P.calculateVOI(d,[{id:'o2',expectedValue:1,informationCost:.1}]);assert.equal(voi.recommendationCouldFlip,true);
const sens=P.sensitivity(d,[{id:'s1',recommendation:'o2',budgetId:'cut-20',assumptions:{risk:.9}}]);assert.equal(sens.recommendationFlips.length,1);assert.equal(sens.budgetScenarioCount,budgets.options.length);
const snap=P.snapshot(d);assert.equal(snap.decisionId,d.id);const persisted=P.persist(d);assert.equal(persisted.ok,true);assert.equal(P.getDecision(d.id).id,d.id);
const over=P.override(d,'actor','o2','Documented reason for adopting an alternative.');assert.equal(over.ok,true);assert.equal(P.override(d,'actor','o2','').ok,false);
assert.equal(P.recordOutcome(d,'1-year',100,90).ok,true);assert.equal(P.detectDrift(d,.05).detected,true);
const artifact=P.exportArtifact(d);assert.equal(P.importArtifact(artifact).ok,true);assert.equal(P.setKillSwitch(true,'maintenance').enabled,true);assert.equal(P.isKilled(),true);assert.equal(P.evaluate(d,()=>({recommended:d.options[0]})).code,'KILL_SWITCH');P.setKillSwitch(false);
const failure=P.recordFailure('TEST','Synthetic validation failure','info');assert.equal(P.listFailures().some(x=>x.id===failure.id),true);
console.log('VIDIK Platform 10 contract: PASS — discovery-first full municipal budget envelope');
