'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const context={console};context.window=context;context.VIDIK_PLATFORM_10={AUDIENCES:['municipal','business','research','public']};
vm.createContext(context);
vm.runInContext(fs.readFileSync('js/vidik-audience-contract-1.js','utf8'),context,{filename:'js/vidik-audience-contract-1.js'});
const A=context.VIDIK_AUDIENCE_CONTRACT_1;
assert.ok(A);
assert.deepStrictEqual(Array.from(A.listAudienceProfiles()),['municipal','business','developer','research','public']);
assert.strictEqual(context.VIDIK_PLATFORM_10.AUDIENCES.includes('developer'),true);
assert.strictEqual(A.getAudienceProfile('enterprise').label,'Business / Enterprise');
assert.strictEqual(A.getAudienceProfile('property').label,'Developer / Project');
const valid={statusQuo:{},options:[],evidence:[],uncertainty:{},opportunityCost:{},equity:{},implementationConstraints:{}};
assert.strictEqual(A.validateAudienceDecision('business',valid).ok,true);
assert.strictEqual(A.validateAudienceDecision('developer',valid).ok,true);
assert.strictEqual(A.validateAudienceDecision('developer',{options:[],evidence:[]}).code,'AUDIENCE_CONTRACT_INCOMPLETE');
assert.strictEqual(A.validateAudienceDecision('unknown',valid).code,'UNKNOWN_AUDIENCE');
assert.strictEqual(A.developerIntegration.provenanceRequired,true);
assert.strictEqual(A.developerIntegration.uncertaintyRequired,true);
console.log('VIDIK audience contract 1: PASS');
