'use strict';
const { recommendationGate, buildStatusQuo, sensitivity, estimateVOI }=require('./decision-engine');
const { optimize }=require('./optimizer');
const { buildTransferSet }=require('./learning-engine');
const { createDecisionArtifact }=require('./artifact-engine');
const { runIntelligenceFoundation }=require('./intelligence-foundation');
const { optimizeResourceAllocationExact }=require('./intelligence-validation');
function text(x){return String(x??'').trim();}
function runDecisionPipeline(problem,candidates=[],context={}){const statusQuo=context.statusQuo?.explicit?context.statusQuo:buildStatusQuo(context.statusQuo||{});const transfers=buildTransferSet(problem,context.comparableCities||[]);const gates=(Array.isArray(candidates)?candidates:[]).map(candidate=>recommendationGate(candidate,{problem,statusQuo}));const optimizer=optimize(problem,candidates,context);const eligible=gates.filter(g=>g.allowed);const selected=optimizer.selected&&eligible.some(g=>g.candidateId===optimizer.selected.candidateId)?optimizer.selected:null;const recommendation=selected?{allowed:true,candidateId:selected.candidateId,reason:'all-gates-passed-and-optimizer-selected'}:{allowed:false,reason:eligible.length?'optimizer-selected-candidate-failed-integration-check':'no-candidate-passed-all-gates'};const blockedByIntegration=optimizer.selected&&!selected?[optimizer.selected.candidateId]:[];const intelligenceFoundation=context.intelligenceFoundation?runIntelligenceFoundation(problem,{...context.intelligenceFoundation,candidates:Array.isArray(context.intelligenceFoundation.candidates)?context.intelligenceFoundation.candidates:candidates,comparableCities:context.comparableCities||context.intelligenceFoundation.comparableCities||[]}):null;const exactResourceAllocation=context.exactResourceAllocation?optimizeResourceAllocationExact(context.exactResourceAllocation.candidates||candidates,context.exactResourceAllocation.budget,context.exactResourceAllocation.options||{}):null;return {problem:text(problem),statusQuo,comparableCityTransfer:transfers,gates,optimizer,exactResourceAllocation,recommendation,blockedByIntegration,intelligenceFoundation,readyForArtifact:recommendation.allowed===true&&(!intelligenceFoundation||intelligenceFoundation.recommendationAuthority===false),rule:'No recommendation may bypass the evidence gates, optimizer, status quo, intelligence-foundation safeguards, exact allocation safeguards, or artifact contract.'};}
function prepareAnalysis(candidate,scenarios=[],voi={}){return {sensitivity:sensitivity(candidate,scenarios),voi:estimateVOI(voi),parameterMutationAllowed:false};}
async function finalizeArtifact(pipeline,input={}){if(!pipeline?.readyForArtifact)throw new Error('orchestrator-recommendation-not-eligible');const gate=pipeline.gates.find(g=>g.candidateId===pipeline.recommendation.candidateId&&g.allowed);if(!gate)throw new Error('orchestrator-selected-gate-missing');return createDecisionArtifact({...input,problem:pipeline.problem,statusQuo:pipeline.statusQuo,recommendation:pipeline.recommendation,evidence:gate.evidence.evidence,parameters:gate.parameters.parameters,opportunityCost:pipeline.optimizer.opportunityCost||{},governance:{...(input.governance||{}),comparableCityEffectsImported:pipeline.comparableCityTransfer.eligible.some(r=>r.causalEffectImported===true),effectsImported:false,parameterMutationAllowed:false,intelligenceFoundationApplied:Boolean(pipeline.intelligenceFoundation),exactAllocationApplied:Boolean(pipeline.exactResourceAllocation)}});}
module.exports={runDecisionPipeline,prepareAnalysis,finalizeArtifact};
